### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by diVineProportion** [PySimpleGUI/PySimpleGUI-YOLO#1]
https://www.dropbox.com/s/0pq7le6fwtbarkc/yolov3.weights?dl=1

**Comment by diVineProportion** [comment]
`wget https://pjreddie.com/media/files/yolov3.weights`

**Comment by PySimpleGUI** [comment]
Fixed and added to readme.

https://www.dropbox.com/s/uf00d4ov6fmw0he/yolov3.weights?dl=1
