### ISSUE TITLE
Custom dataset with own weights

### ISSUE THREAD

**Issue by Whisper94** [PySimpleGUI/PySimpleGUI-YOLO#2]
Hello. Thank you for your amazing work with GUI. I'de like to use with this GUI my own weights from own dataset. Could you explain if I need to change code -> downloading from darknet (#56 net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)) or I should only change the paths to my own classes and weights files/directories?
If I run "python yolo_video.py" I get the following error:

[INFO] loading YOLO from disk...
Traceback (most recent call last):
  File "yolo_video.py", line 56, in <module>
    net = cv2.dnn.readNetFromDarknet(configPath, weightsPath)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_importer.cpp:214: error: (-212:Parsing error) Failed to parse NetParameter file: yolo-coco\yolov3.weights in function 'cv::dnn::dnn4_v20190902::readNetFromDarknet'

if I try to change the original weights from YOLO to my own as .h5 then I get:

[INFO] loading YOLO from disk...
Traceback (most recent call last):
  File "yolo.py", line 65, in <module>
    net = cv2.dnn.readNet(configPath, weightsPath)
cv2.error: OpenCV(4.2.0) C:\projects\opencv-python\opencv\modules\dnn\src\darknet\darknet_io.cpp:712: error: (-213:The function/feature is not implemented) Transpose the weights (except for convolutional) is not implemented in function 'cv::dnn::darknet::ReadDarknetFromWeightsStream'

Thank you for your help!

**Comment by PySimpleGUI** [comment]
You'll want to sign up for a course from PyImageSearch to learn more about how to do something like this.  This particular project is simply one of his free tutorials.  I don't have the knowledge to tell you what to do, but his courses surely will.
